// components/custom/CustomFilter.vue
<template>
  <div v-show="filterShowFlag">
    <v-container fluid>
      <b style="vertical-align: middle">{{ $t('search_query') }}</b>
      <template v-if="keyword">
        <v-chip
          v-for="(value, index) in keyword"
          :key="index"
          style="white-space: normal; word-wrap: break-word"
          class="ma-1"
          close
          color="primary"
          label
          text-color="white"
          @click:close="removeKey(value, 'keyword')"
        >
          {{ $t('keyword') }}: {{ value }}
        </v-chip>
      </template>

      <template v-for="(type, t) in ['fc', 'q']">
        <template v-for="(agg, label) in advanced[type]">
          <span :key="t + '-' + label">
            <template v-for="method in ['+', '-']">
              <v-chip
                v-for="(value, m) in agg[method]"
                :key="m"
                style="white-space: normal; word-wrap: break-word"
                class="ma-1"
                close
                :color="method === '+' ? 'primary' : 'grey'"
                label
                text-color="white"
                @click:close="
                  removeAdvanced(
                    label,
                    [method === '+' ? value : '-' + value],
                    type
                  )
                "
              >
                <v-icon v-if="method !== '+'" class="mr-1"
                  >mdi-minus-box</v-icon
                >
                {{ getLabel(label) }}:
                <span
                  class="ml-1"
                  :class="label.includes('fc-Phone/Word') ? 'phone' : ''"
                  >{{ value }}</span
                >
              </v-chip>
            </template>
          </span>
        </template>
      </template>

      <v-btn
        small
        text
        :to="localePath({ name: 'search', query: { u: $route.query.u } })"
        class="error--text ma-1"
      >
        <v-icon>mdi-close</v-icon> {{ $t('clear') }}
      </v-btn>
    </v-container>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'

@Component
export default class CustomFilter extends Vue {
  get keyword() {
    const keyword = this.$store.state.keyword
    return Array.isArray(keyword) ? keyword : [keyword]
  }

  get advanced() {
    return this.$store.state.advanced
  }

  removeKey(value: string, label: string) {
    const data: any = {
      label,
      value: [value],
    }
    this.$store.commit('removeKey', data)
    this.$router.push(
      this.localePath({
        name: 'search',
        query: this.$searchUtils.getSearchQueryFromQueryStore(
          this.$store.state,
          this.$route.query.u
        ),
      }),
      () => {},
      () => {}
    )
  }

  removeAdvanced(label: string, values: string[], type: string) {
    this.$store.commit('removeAdvanced', {
      label,
      values,
      type,
    })

    // push 処理
    const query: any = this.$searchUtils.getSearchQueryFromQueryStore(
      this.$store.state,
      this.$route.query.u
    )

    this.$router.push(
      this.localePath({
        name: 'search',
        query,
      }),
      () => {},
      () => {}
    )
  }

  get filterShowFlag(): boolean {
    let flag = false
    if (
      this.keyword.length > 0 ||
      Object.keys(this.advanced.fc).length > 0 ||
      Object.keys(this.advanced.q).length > 0
    ) {
      flag = true
    }
    return flag
  }

  getLabel(term: string): string {
    const termLabels = null
    const types: any = {
      'fc-': this.$t('facet'),
      'q-': this.$t('advanced'),
    }

    let result: string = ''

    for (const type in types) {
      if (term.startsWith(type)) {
        const label = term.replace(type, '')

        console.log(label, termLabels)

        result =
          '[' +
          types[type] +
          '] ' +
          this.$t((termLabels && termLabels[label] ? termLabels[label] : label))

        break
      }
    }

    return result
  }
}
</script>

// src/app/[locale]/search/custom-filter.tsx
'use client'

import { useTranslations } from 'next-intl'
import { useSearchStore } from '@/lib/use-search-store'
import { getSearchQueryFromQueryStore } from '@/lib/search-utils'
import { useRouter } from '@/i18n/navigation'
import { useSearchParams } from 'next/navigation'
import { X, MinusSquare } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'

export function CustomFilter() {
  const t = useTranslations()
  const router = useRouter()
  const searchParams = useSearchParams()
  const keyword = useSearchStore((s) => s.keyword)
  const advanced = useSearchStore((s) => s.advanced)

  const hasFilters =
    keyword.length > 0 ||
    Object.keys(advanced.fc).length > 0 ||
    Object.keys(advanced.q).length > 0

  if (!hasFilters) return null

  const removeKey = (value: string) => {
    useSearchStore.getState().removeKey({ label: 'keyword', value: [value] })
    const state = useSearchStore.getState()
    const query = getSearchQueryFromQueryStore(state, searchParams?.get('u') || undefined)
    const params = new URLSearchParams()
    for (const [key, val] of Object.entries(query)) {
      if (Array.isArray(val)) val.forEach((v) => params.append(key, v))
      else params.append(key, val)
    }
    router.push(`/search?${params.toString()}`)
  }

  const removeAdvanced = (label: string, values: string[], type: string) => {
    useSearchStore.getState().removeAdvanced({ label, values, type })
    const state = useSearchStore.getState()
    const query = getSearchQueryFromQueryStore(state, searchParams?.get('u') || undefined)
    const params = new URLSearchParams()
    for (const [key, val] of Object.entries(query)) {
      if (Array.isArray(val)) val.forEach((v) => params.append(key, v))
      else params.append(key, val)
    }
    router.push(`/search?${params.toString()}`)
  }

  const getLabel = (term: string): string => {
    const types: Record<string, string> = {
      'fc-': t('facet'),
      'q-': t('advanced'),
    }
    for (const [prefix, typeLabel] of Object.entries(types)) {
      if (term.startsWith(prefix)) {
        const label = term.replace(prefix, '')
        return `[${typeLabel}] ${t(label)}`
      }
    }
    return term
  }

  return (
    <div className="bg-muted">
      <div className="max-w-7xl mx-auto px-4 py-3 flex items-center flex-wrap">
        <span className="font-bold mr-2 text-sm">{t('search_query')}</span>

        {keyword.map((value, i) => (
          <Badge
            key={`kw-${i}`}
            className="m-1 gap-1"
          >
            {t('keyword')}: {value}
            <button onClick={() => removeKey(value)} className="ml-0.5 hover:opacity-80" aria-label={`${t('remove')} ${value}`}>
              <X className="w-3 h-3" />
            </button>
          </Badge>
        ))}

        {(['fc', 'q'] as const).map((type) =>
          Object.entries(advanced[type]).map(([label, agg]) =>
            (['+', '-'] as const).map((method) =>
              agg[method].map((value, m) => (
                <Badge
                  key={`${type}-${label}-${method}-${m}`}
                  variant={method === '+' ? 'default' : 'destructive'}
                  className="m-1 gap-1"
                >
                  {method !== '+' && <MinusSquare className="w-3 h-3" />}
                  {getLabel(label)}:
                  <span className={label.includes('fc-Phone/Word') ? 'phone' : ''}>
                    {value}
                  </span>
                  <button
                    onClick={() =>
                      removeAdvanced(label, [method === '+' ? value : '-' + value], type)
                    }
                    className="ml-0.5 hover:opacity-80"
                    aria-label={`${t('remove')} ${value}`}
                  >
                    <X className="w-3 h-3" />
                  </button>
                </Badge>
              ))
            )
          )
        )}

        <Button
          variant="ghost"
          size="sm"
          onClick={() => {
            const u = searchParams?.get('u')
            const params = u ? `?u=${u}` : ''
            router.push(`/search${params}`)
          }}
          className="text-destructive hover:text-destructive ml-1"
        >
          <X className="w-4 h-4 mr-1" /> {t('clear')}
        </Button>
      </div>
    </div>
  )
}
