// components/search/StatsSearchResult.vue
<template>
  <div>
    <template v-for="(obj, index) in facetOptions">
      <v-card
        v-if="
          aggregations[index] &&
          aggregations[index].buckets &&
          aggregations[index].buckets.length > 0
        "
        :key="index"
        no-body
        class="mb-10"
      >
        <v-card-title class="grey lighten-2">{{
          obj.label.startsWith('_') ? $t(obj.label.slice(1)) : $t(obj.label)
        }}</v-card-title>

        <div class="pa-5">
          <Chart
            :height="200"
            class="mb-4"
            :buckets="aggregations[index].buckets"
          ></Chart>
        </div>
      </v-card>
    </template>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'
import Chart from '~/components/search/TestChart.vue'

@Component({
  components: {
    Chart,
  },
})
export default class StatsSearchResult extends Vue {
  get aggregations() {
    return this.$store.state.result.aggregations
  }

  get facetOptions() {
    return this.$store.state.facetOptions
  }
}
</script>

// src/app/[locale]/search/stats-search-result.tsx
'use client'

import { useSearchStore } from '@/lib/use-search-store'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { BarChart } from './bar-chart'

export function StatsSearchResult() {
  const result = useSearchStore((s) => s.result) as Record<string, unknown>
  const facetOptions = useSearchStore((s) => s.facetOptions)
  const aggregations = (result.aggregations || {}) as Record<string, { buckets: { key: string; doc_count: number }[] }>

  return (
    <div>
      {Object.entries(facetOptions).map(([key, opt]) => {
        const agg = aggregations[key]
        if (!agg || !agg.buckets || agg.buckets.length === 0) return null
        return (
          <Card key={key} className="mb-10">
            <CardHeader>
              <CardTitle className="text-lg">{opt.label}</CardTitle>
            </CardHeader>
            <CardContent>
              <BarChart buckets={agg.buckets} height={200} />
            </CardContent>
          </Card>
        )
      })}
    </div>
  )
}
