// app/[locale]/search/facet-search-options.tsx
'use client'

import { useSearchStore } from '@/store/use-search-store'
import { CustomFacetOption } from './custom-facet-option'

export function FacetSearchOptions() {
  const result = useSearchStore((s) => s.result) as Record<string, unknown>
  const facetOptions = useSearchStore((s) => s.facetOptions)
  const aggregations = (result.aggregations || {}) as Record<
    string,
    { buckets: { key: string; doc_count: number }[] }
  >

  return (
    <div>
      {Object.entries(facetOptions).map(([key, opt]) => {
        const agg = aggregations[key]
        if (!agg) return null
        return (
          <CustomFacetOption
            key={key}
            term={key}
            label={opt.label}
            buckets={agg.buckets}
          />
        )
      })}
    </div>
  )
}

// components/search/FacetSearchOptions.vue
<template>
  <div>
    <!-- facets -->
    <template v-for="(label, index) in facetLabels">
      <FacetOption
        v-if="aggregations[index]"
        :key="index"
        :term="index"
        :label="label"
        :buckets="aggregations[index].buckets"
        :query="query"
        class="mb-5"
      />
    </template>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'
import FacetOption from '~/components/custom/FacetOption.vue'

@Component({
  components: {
    FacetOption,
  },
})
export default class FacetSearchOptions extends Vue {
  get aggregations() {
    return this.$store.state.result.aggregations
  }

  get facetLabels() {
    return this.$store.state.facetLabels
  }

  get query() {
    return this.$store.state.query
  }
}
</script>
