// app/[locale]/search/hpdb-search-result.tsx
'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'
import { Link } from '@/i18n/navigation'
import { useSearchStore } from '@/store/use-search-store'
import { CustomSplit } from './custom-split'
import { Filter, ArrowRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog'

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || ''

export function HpdbSearchResult() {
  const t = useTranslations()
  const result = useSearchStore((s) => s.result) as Record<string, unknown>
  const selected = useSearchStore((s) => s.selected)
  const setSelected = useSearchStore((s) => s.setSelected)
  const index = useSearchStore((s) => s.index)
  const dataAll = useSearchStore((s) => s.data)
  const [dialog, setDialog] = useState(false)
  const [selectedTemp, setSelectedTemp] = useState<string[]>([])

  const hits = (result.hits as Record<string, unknown[]>)?.hits || []

  const select = (id: string) => {
    const newSelected = [...selected]
    const idx = newSelected.indexOf(id)
    if (idx === -1) newSelected.push(id)
    else newSelected.splice(idx, 1)
    setSelected(newSelected)
  }

  const getLabel = (id: string) => {
    if (!index || !index._id || !index._id[id]) return null
    const seq = index._id[id][0]
    return dataAll[seq] as Record<string, unknown>
  }

  const compare = () => {
    const param = selected.map((id) => {
      const obj = getLabel(id)
      if (!obj) return null
      const source = obj._source as Record<string, string[]>
      const related = source._relatedLink[0]
      const spl = related.split('&')
      const manifest = spl[0].split('=')[1]
      const canvas = spl[1].split('=')[1] + '#xywh=' + spl[2].split('=')[1]
      return { manifest, canvas }
    }).filter(Boolean)

    const url =
      BASE_URL +
      '/mirador/index.html?params=' +
      encodeURIComponent(JSON.stringify(param)) +
      '&layout=1x' +
      selected.length
    window.open(url, '_blank')
  }

  const getMiradorUrl = (source: Record<string, string[]>) => {
    const related = source._relatedLink[0]
    const spl = related.split('&')
    const manifest = spl[0].split('=')[1]
    const canvas = spl[1].split('=')[1] + '#xywh=' + spl[2].split('=')[1]
    const params = JSON.stringify([{ manifest, canvas }])
    return BASE_URL + '/mirador/index.html?params=' + encodeURIComponent(params)
  }

  const getUtaUrl = (source: Record<string, string[]>) => {
    const params = source._relatedLink[0].split('?')[1].split('&')
    const page = params[1].split('/canvas/p')[1]
    const xywh = params[2].split('=')[1]
    const id = params[0].split('/manifest/')[1].split('/')[0]
    return (
      'https://iiif.dl.itc.u-tokyo.ac.jp/repo/s/asia/document/' +
      id +
      '#?c=0&m=0&s=0&cv=' +
      (Number(page) - 1) +
      '&xywh=' +
      xywh
    )
  }

  return (
    <div>
      <div className="my-4 text-right flex justify-end gap-2">
        <Button onClick={compare} size="sm">
          {t('compare_items', { count: selected.length })}
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => { setSelectedTemp([]); setDialog(true) }}
        >
          {t('list')}
        </Button>
      </div>

      {/* Selected items dialog */}
      <Dialog open={dialog} onOpenChange={setDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('selected_items')}</DialogTitle>
            <DialogDescription>{selected.length} items selected</DialogDescription>
          </DialogHeader>
          <div className="max-h-72 overflow-y-auto">
            {selected.map((id, i) => {
              const obj = getLabel(id)
              const label = obj ? (obj._source as Record<string, string[]>)?._label?.[0] : id
              return (
                <label key={i} className="flex items-center gap-2 py-1.5 cursor-pointer">
                  <Checkbox
                    checked={selectedTemp.includes(id)}
                    onCheckedChange={() => {
                      setSelectedTemp((prev) =>
                        prev.includes(id)
                          ? prev.filter((x) => x !== id)
                          : [...prev, id]
                      )
                    }}
                  />
                  <span className="text-sm">{label}</span>
                </label>
              )
            })}
          </div>
          <DialogFooter className="gap-2">
            <Button onClick={() => setDialog(false)} size="sm">
              {t('close')}
            </Button>
            <Button
              variant="destructive"
              size="sm"
              onClick={() => {
                const newSelected = selected.filter((id) => !selectedTemp.includes(id))
                setSelected(newSelected)
                setSelectedTemp([])
              }}
            >
              {t('delete')}
            </Button>
            <Button
              variant="destructive"
              size="sm"
              onClick={() => setSelected([])}
            >
              {t('reset')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {hits.map((obj: unknown, i: number) => {
        const item = obj as { _id: string; _source: Record<string, string[]> }
        const source = item._source

        return (
          <Card key={i} className="mb-5">
            <CardContent className="p-4">
              <div className="flex flex-col sm:flex-row gap-4">
                <div className="sm:w-1/3 space-y-1 text-sm">
                  <div>
                    <b>{t('Item Label')}</b>&nbsp;
                    <CustomSplit data={source['Item Label']} field="Item Label Mod" />
                  </div>
                  <div>
                    <b>{t('Hieratic No')}</b>&nbsp;
                    <CustomSplit data={source['Hieratic No']} field="Hieratic No Mod" />
                  </div>
                  <div>
                    <b>{t('Hieroglyph No')}</b>&nbsp;
                    <CustomSplit data={source['Hieroglyph No']} field="Hieroglyph No Mod" />
                  </div>
                  <div className="flex items-center flex-wrap">
                    <b>{t('Item Type')}</b>&nbsp;
                    {source['Item Type']?.map((v, j) => (
                      <span key={j} className="inline-flex items-center">
                        {t(v)}
                        <Link href={`/search?fc-Item+Type=${v}`} className="ml-1 inline-flex items-center justify-center w-5 h-5 rounded border border-border bg-muted hover:bg-accent transition-colors" title={t('filter_by_this')}>
                          <Filter className="w-3 h-3" />
                        </Link>
                        {j < source['Item Type'].length - 1 && <>&nbsp;+&nbsp;</>}
                      </span>
                    ))}
                    {source['Unit'] && source['Unit'].length > 0 && (
                      <>
                        &nbsp;<b>{t('Unit')}</b>&nbsp;
                        {source['Unit'].map((v, j) => (
                          <span key={j} className="inline-flex items-center">
                            {t(v)}
                            <Link href={`/search?fc-Unit=${v}`} className="ml-1 inline-flex items-center justify-center w-5 h-5 rounded border border-border bg-muted hover:bg-accent transition-colors" title={t('filter_by_this')}>
                              <Filter className="w-3 h-3" />
                            </Link>
                            {j < source['Unit'].length - 1 && <>&nbsp;+&nbsp;</>}
                          </span>
                        ))}
                      </>
                    )}
                  </div>
                  {source['Numeral'] && source['Numeral'].length > 0 && (
                    <div className="flex items-center flex-wrap">
                      <b>{t('Numeral')}</b>&nbsp;
                      {source['Numeral'].map((v, j) => (
                        <span key={j} className="inline-flex items-center">
                          {v}
                          <Link href={`/search?fc-Numeral=${v}`} className="ml-1 inline-flex items-center justify-center w-5 h-5 rounded border border-border bg-muted hover:bg-accent transition-colors" title={t('filter_by_this')}>
                            <Filter className="w-3 h-3" />
                          </Link>
                          {j < source['Numeral'].length - 1 && ', '}
                        </span>
                      ))}
                    </div>
                  )}
                  {source['Phone/Word'] && source['Phone/Word'].length > 0 && (
                    <div className="flex items-center flex-wrap">
                      <b>{t('Phone/Word')}</b>&nbsp;
                      {source['Phone/Word'].map((v, j) => {
                        const clean = v.replace('(', '').replace(')', '')
                        return (
                          <span key={j} className="inline-flex items-center">
                            {v.startsWith('(') && '('}
                            <span className="phone">{clean}</span>
                            <Link href={`/search?fc-Phone%2FWord+Mod=${encodeURIComponent(clean)}`} className="ml-1 inline-flex items-center justify-center w-5 h-5 rounded border border-border bg-muted hover:bg-accent transition-colors" title={t('filter_by_this')}>
                              <Filter className="w-3 h-3" />
                            </Link>
                            {v.endsWith(')') && ')'}
                            {j < source['Phone/Word'].length - 1 && ', '}
                          </span>
                        )
                      })}
                    </div>
                  )}
                  <div>
                    <b>{t('Vol')}</b>&nbsp;{source.Vol?.[0]},&nbsp;
                    <b>{t('Page')}</b>&nbsp;{source.Page?.[0]},&nbsp;
                    <b>{t('Order')}</b>&nbsp;{source.Order?.[0]}
                  </div>
                  {source.Note?.[0] && source.Note[0] !== '' && (
                    <div>
                      <b>{t('Note')}</b>&nbsp;{source.Note[0]}
                    </div>
                  )}
                  <label className="flex items-center mt-2 cursor-pointer gap-2 text-sm text-muted-foreground">
                    <Checkbox
                      checked={selected.includes(item._id)}
                      onCheckedChange={() => select(item._id)}
                    />
                    {t('compare')}
                  </label>
                </div>

                <div className="sm:w-2/3 flex flex-col items-center">
                  <Link href={`/item/${item._id}`}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={source._thumbnail?.[0]}
                      alt={source._label?.[0] || ''}
                      className="max-h-32 object-contain mx-auto"
                    />
                  </Link>
                  <div className="mt-3">
                    <Link href={`/item/${item._id}`} className="no-underline">
                      <Button variant="outline" size="sm" className="gap-1.5">
                        {t('view_detail')}
                        <ArrowRight className="w-3.5 h-3.5" />
                      </Button>
                    </Link>
                  </div>
                  <div className="mt-2 flex justify-center gap-2">
                    <a href={getMiradorUrl(source)} target="_blank" rel="noopener noreferrer">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={BASE_URL + '/img/icons/mirador.svg'} width="30" alt="Mirador" />
                    </a>
                    <a href={getUtaUrl(source)} target="_blank" rel="noopener noreferrer">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={BASE_URL + '/img/icons/ut.ico'} width="30" alt={t('uta')} />
                    </a>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        )
      })}
    </div>
  )
}

// components/custom/HpdbSearchResult.vue
<template>
  <div>
    <div class="my-4 text-right">
      <v-btn color="primary" class="ma-2" @click="compare">
        <template v-if="$i18n.locale == 'ja'">
          {{ selected.length }} 件のアイテムを比較
        </template>
        <template v-else> Compare {{ selected.length }} items </template>
      </v-btn>

      <v-dialog v-model="dialog" scrollable max-width="600px">
        <template #activator="{ on }">
          <v-btn class="ma-2" v-on="on">{{ $t('list') }}</v-btn>
        </template>
        <v-card>
          <v-card-title>{{ $t('selected_items') }}</v-card-title>
          <v-divider></v-divider>
          <v-card-text style="height: 300px">
            <v-list-item-group>
              <v-list-item
                v-for="(id, index) in selected"
                :key="'selected_' + index"
              >
                <v-checkbox
                  v-model="selectedTemporary"
                  color="primary"
                  :label="getLabel(id)._source._label[0]"
                  :value="id"
                ></v-checkbox>
              </v-list-item>
            </v-list-item-group>
          </v-card-text>
          <v-divider></v-divider>

          <v-card-actions>
            <v-btn color="primary" @click="dialog = false">{{
              $t('close')
            }}</v-btn>
            <v-btn color="error" @click="deleteSelected">{{
              $t('delete')
            }}</v-btn>
            <v-btn color="error" @click="selected = []">{{
              $t('reset')
            }}</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </div>

    <v-card
      v-for="(obj, index) in results"
      :key="index"
      flat
      outlined
      class="mb-5"
    >
      <v-card-text>
        <v-row>
          <v-col cols="12" sm="4">
            
            <span>
              <b>{{ $t('Item Label') }}</b>
              &nbsp;
               <CustomSplit
                :data="obj._source['Item Label']"
                field="Item Label Mod"
              />
            </span>

            <br />

            <span>
              <b>{{ $t('Hieratic No') }}</b>
              &nbsp;
              <CustomSplit
                :data="obj._source['Hieratic No']"
                field="Hieratic No Mod"
              />
            </span>

            <br />
            <span>
              <b>{{ $t('Hieroglyph No') }}</b>
              &nbsp;
              <CustomSplit
                :data="obj._source['Hieroglyph No']"
                field="Hieroglyph No Mod"
              />
            </span>
            <br />

            <span>
              <b>{{ $t('Item Type') }}</b>
              &nbsp;
              <template v-for="(value, index2) in obj._source['Item Type']">
                <nuxt-link
                  :key="index2"
                  :to="
                    localePath({
                      name: 'search',
                      query: {
                        'fc-Item Type': value,
                      },
                    })
                  "
                  >{{ $t(value) }}</nuxt-link
                >
                <span
                  v-show="index2 != obj._source['Item Type'].length - 1"
                  :key="'it_' + index2"
                  >&nbsp;+&nbsp;</span
                >
              </template>
            </span>

            &nbsp;

            <span v-if="obj._source['Unit'] && obj._source['Unit'].length > 0">
              <b>{{ $t('Unit') }}</b>
              &nbsp;
              <template v-for="(value, index2) in obj._source['Unit']">
                <nuxt-link
                  :key="index2"
                  :to="
                    localePath({
                      name: 'search',
                      query: {
                        'fc-Unit': value,
                      },
                    })
                  "
                  >{{ $t(value) }}</nuxt-link
                >
                <span
                  v-show="index2 != obj._source['Unit'].length - 1"
                  :key="'unit_' + index2"
                  >&nbsp;+&nbsp;</span
                >
              </template>
            </span>

            <br />

            <div
              v-if="obj._source['Numeral'] && obj._source['Numeral'].length > 0"
            >
              <b>{{ $t('Numeral') }}</b>

              &nbsp;
              <template v-for="(value, index2) in obj._source['Numeral']">
                <nuxt-link
                  :key="index2"
                  :to="
                    localePath({
                      name: 'search',
                      query: {
                        'fc-Numeral': value,
                      },
                    })
                  "
                  >{{ value }}</nuxt-link
                >
                <span
                  v-show="index2 != obj._source['Numeral'].length - 1"
                  :key="'numeral_' + index2"
                  >,&nbsp;</span
                >
              </template>
            </div>

            <div v-if="obj._source['Phone/Word'].length > 0">
              <b>{{ $t('Phone/Word') }}</b
              >&nbsp;
              <template v-for="(value, index2) in obj._source['Phone/Word']">
                <span :key="index2">
                  <span v-if="value.split('(').length > 1">(</span>

                  <nuxt-link
                    class="phone"
                    :to="
                      localePath({
                        name: 'search',
                        query: {
                          'fc-Phone/Word Mod': value
                            .replace('(', '')
                            .replace(')', ''),
                        },
                      })
                    "
                    >{{ value.replace('(', '').replace(')', '') }}</nuxt-link
                  >
                  <span v-if="value.split(')').length > 1">)</span>
                  <span v-show="index2 != obj._source['Phone/Word'].length - 1"
                    >,&nbsp;</span
                  >
                </span>
              </template>
            </div>

            <span>
              <b>{{ $t('Vol') }}</b>
              &nbsp;{{ obj._source.Vol[0] }},&nbsp;
              <b>{{ $t('Page') }}</b>
              &nbsp;{{ obj._source.Page[0] }},&nbsp;

              <b>{{ $t('Order') }}</b>
              &nbsp;{{ obj._source.Order[0] }}
            </span>
            <br />
            <template v-if="obj._source.Note[0] != ''">
              <span>
                <b>{{ $t('Note') }}</b>
                &nbsp;{{ obj._source.Note[0] }}
              </span>
              <br />
            </template>

            <v-switch
              :value="selected.includes(obj._id)"
              @change="select(obj._id)"
            ></v-switch>
          </v-col>
          <v-col cols="12" sm="8">
            <div class="mb-5" v-if="false">
              <nuxt-link
                :to="
                  localePath({
                    name: 'item-id',
                    params: { id: obj._id },
                  })
                "
              >
                {{ $t("view_detail") }}
              </nuxt-link>
            </div>
            <nuxt-link
              :to="
                localePath({
                  name: 'item-id',
                  params: { id: obj._id },
                })
              "
            >
              <v-img
                :src="obj._source._thumbnail[0]"
                max-height="120px"
                contain
              />
            </nuxt-link>

            <div class="text-right">
              <v-tooltip bottom>
                <template #activator="{ on }">
                  <v-btn
                    icon
                    class="mt-2"
                    target="_blank"
                    :href="obj._source._relatedLink[0]"
                    v-on="on"
                    ><img
                      :src="baseUrl + '/img/icons/icp-logo.svg'"
                      width="30px"
                  /></v-btn>
                </template>
                <span>{{ 'IIIF Curation Viewer' }}</span>
              </v-tooltip>

              <v-tooltip bottom>
                <template #activator="{ on }">
                  <v-btn
                    class="mt-2"
                    icon
                    target="_blank"
                    :href="getUrl(obj._source)"
                    v-on="on"
                    ><img :src="baseUrl + '/img/icons/ut.ico'" width="30px"
                  /></v-btn>
                </template>
                <span>{{ $t('uta') }}</span>
              </v-tooltip>
            </div>
          </v-col>
        </v-row>
      </v-card-text>
    </v-card>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'

@Component({
  components: {},
})
export default class ListSearchResult extends Vue {
  baseUrl: string = process.env.BASE_URL || ''

  get results() {
    return this.$store.state.result.hits.hits
  }

  get query() {
    return this.$store.state.query
  }

  get selected() {
    return this.$store.state.selected
  }

  set selected(value) {
    this.$store.commit('setSelected', value)
  }

  selectedTemporary: string[] = []

  dialog: boolean = false

  get index() {
    return this.$store.state.index
  }

  get dataAll() {
    return this.$store.state.data
  }

  select(id: string) {
    const selected = JSON.parse(JSON.stringify(this.selected))
    const index = selected.indexOf(id)
    if (index === -1) {
      selected.push(id)
    } else if (index !== -1) {
      selected.splice(index, 1)
    }
    this.selected = selected
  }

  compare() {
    const param = []

    for (let i = 0; i < this.selected.length; i++) {
      const id = this.selected[i]
      const obj = this.getLabel(id)
      const related = obj._source._relatedLink[0]

      const relatedSpl = related.split('&')
      const manifest = relatedSpl[0].split('=')[1]

      const canvas =
        relatedSpl[1].split('=')[1] + '#xywh=' + relatedSpl[2].split('=')[1]

      param.push({
        manifest,
        canvas,
      })
    }

    const url =
      this.baseUrl +
      '/mirador/?params=' +
      encodeURIComponent(JSON.stringify(param)) +
      '&layout=' +
      this.selected.length +
      'x1'
    open(url, '_blank')
  }

  resetSelected() {
    this.selected = []
    const hits = this.results.hits.hits
    for (let i = 0; i < hits.length; i++) {
      const obj = hits[i]
      obj.selected = false
    }
  }

  deleteSelected() {
    const selectedTemporary = this.selectedTemporary
    const selected = JSON.parse(JSON.stringify(this.selected))
    for (let i = 0; i < selectedTemporary.length; i++) {
      const id = selectedTemporary[i]
      const index = selected.indexOf(id)
      selected.splice(index, 1)
    }

    this.selected = selected
    this.selectedTemporary = []
  }

  getLabel(id: string) {
    const seq = this.index._id[id][0]
    const obj = this.dataAll[seq]
    return obj
  }

  getUrl(obj: any) {
    const params = obj._relatedLink[0].split('?')[1].split('&')
    const page = params[1].split('/canvas/p')[1]
    const xywh = params[2].split('=')[1]
    const id = params[0].split('/manifest/')[1].split('/')[0]
    const url =
      'https://iiif.dl.itc.u-tokyo.ac.jp/repo/s/asia/document/' +
      id +
      '#?c=0&m=0&s=0&cv=' +
      (Number(page) - 1) +
      '&xywh=' +
      xywh
    return url
  }
}
</script>
