// components/custom/CustomFacetOption.vue
<template>
  <v-expansion-panels
    v-if="buckets.length > 0 || getArray('-').length > 0"
    flat
    :value="openFlag ? 0 : null"
  >
    <v-expansion-panel>
      <v-expansion-panel-header class="grey lighten-2"
        ><b>
          <!-- {{ label.startsWith('_') ? $t(label.slice(1)) : $t(label) }} -->
          {{ label.startsWith('_') ? label.slice(1) : label }}
          <small>({{ message }})</small>
        </b></v-expansion-panel-header
      >
      <v-expansion-panel-content>
        <v-list dense>
          <div style="max-height: 400px" class="overflow-y-auto">
            <template v-for="(bucket, index) in buckets">
              <v-list-item :key="'bucket_' + index">
                <v-list-item-content
                  class="my-0 py-0"
                  style="word-break: break-word"
                >
                  <v-checkbox
                    v-model="values[index]"
                    :class="term.includes('Phone/Word') ? 'phone' : ''"
                    class="mb-0 mt-1 ml-1 py-0"
                    align="center"
                    dense
                    x-small
                    color="primary"
                    :label="
                      ['Item Type', 'Sub Type', 'Unit'].includes(term)
                        ? $t(bucket.key)
                        : bucket.key
                    "
                    @change="change('fc-' + term, bucket.key)"
                  ></v-checkbox>
                </v-list-item-content>

                <v-list-item-action class="my-0 py-0">{{
                  bucket.doc_count.toLocaleString()
                }}</v-list-item-action>

                <v-list-item-action class="my-0 py-0">
                  <v-btn
                    v-show="!values[index]"
                    icon
                    x-small
                    @click="
                      remove({
                        label: 'fc-' + term,
                        values: ['-' + bucket.key],
                        type: 'fc',
                      })
                    "
                  >
                    <v-icon color="grey lighten-1">mdi-close-circle</v-icon>
                  </v-btn>
                </v-list-item-action>
              </v-list-item>

              <v-divider :key="`divider-${index}`"></v-divider>
            </template>
          </div>

          <!-- NOT -->

          <template v-for="(bucket, index) in getArray('-')">
            <v-divider :key="`divider-not-${index}`"></v-divider>
            <v-list-item
              :key="index"
              @click="
                add({
                  label: 'fc-' + term,
                  values: ['-' + bucket],
                  type: 'fc',
                })
              "
            >
              <v-list-item-action>
                <v-icon color="red darken-3">mdi-minus-box</v-icon>
              </v-list-item-action>
              <v-list-item-content>
                {{ term == 'jp' ? $t(bucket) : bucket }}
              </v-list-item-content>
            </v-list-item>

            <v-divider :key="`divider-not2-${index}`"></v-divider>
          </template>

          <v-list-item>
            <v-list-item-action>
              <!-- small  -->
              <v-btn color="primary" @click="updateQuery()">{{
                $t('update')
              }}</v-btn>
            </v-list-item-action>
          </v-list-item>
        </v-list>
      </v-expansion-panel-content>
    </v-expansion-panel>
  </v-expansion-panels>
</template>

<script lang="ts">
import { Vue, Prop, Watch, Component } from 'nuxt-property-decorator'
// import { queryStore } from '~/store'

@Component
export default class FacetOption extends Vue {
  @Prop({
    default: '',
    required: true,
  })
  label!: string

  @Prop({
    default: '',
    required: true,
  })
  term!: string

  @Prop({
    required: true,
    default() {
      return []
    },
  })
  buckets: any

  created() {
    this.main()
  }

  @Watch('buckets')
  watchBuckets() {
    this.main()
  }

  values: boolean[] = []

  main() {
    const values: boolean[] = []
    // 選択済みの値設定
    for (let i = 0; i < this.buckets.length; i++) {
      const bucket = this.buckets[i]
      values.push(this.checked('fc-' + this.term, bucket.key))
    }

    this.values = values
  }

  openFlag: boolean = !!(
    this.$store.state.facetOptions[this.term].open ||
    this.getArray('-').length > 0 ||
    this.getArray('+').length > 0
  )

  get facetOptions() {
    return this.$store.state.facetOptions
  }

  changeFacetFlags() {
    this.$store.commit('changeFacetFlags', {
      label: this.term,
      value: !this.openFlag,
    })
    this.openFlag = !this.openFlag
  }

  getArray(type: string): string[] {
    const label = 'fc-' + this.term
    if (!this.$store.state.advanced.fc) {
      return []
    }
    if (this.$store.state.advanced.fc[label]) {
      return this.$store.state.advanced.fc[label][type]
    } else {
      return []
    }
  }

  // 完成
  change(label: string, value: string) {
    const obj = this.$store.state.advanced.fc[label]
    if (obj && obj['+'].includes(value)) {
      this.$store.commit('removeAdvanced', {
        label,
        values: [value],
        type: 'fc',
      })
    } else {
      this.$store.commit('setAdvanced', {
        label,
        values: [value],
        type: 'fc',
      })
    }
  }

  remove(data: { [keyword: string]: string }) {
    this.$store.commit('setAdvanced', data)
    this.updateQuery()
  }

  add(data: { [keyword: string]: string }) {
    this.$store.commit('removeAdvanced', data)
    this.updateQuery()
  }

  updateQuery() {
    const query = this.$searchUtils.getSearchQueryFromQueryStore(
      this.$store.state,
      this.$route.query.u
    )
    query.from = 0
    this.$router.push(
      this.localePath({
        name: 'search',
        query,
      }),
      () => {},
      () => {}
    )
  }

  checked(label: string, value: string) {
    const obj = this.$store.state.advanced.fc[label]
    if (obj && obj['+'].includes(value)) {
      return true
    } else {
      return false
    }
  }

  get message() {
    const size: number = this.buckets.length
    let prefix: string = ''
    const suffix: string = this.$i18n.locale === 'ja' ? '件' : ''
    if (size === 50) {
      prefix = this.$i18n.locale === 'ja' ? '上位' : 'Top '
    }
    return prefix + size.toLocaleString() + suffix
  }
}
</script>
<style>
.v-expansion-panel-content__wrap {
  padding: 0 !important;
}
</style>

// app/[locale]/search/custom-facet-option.tsx
'use client'

import { useState, useMemo, useCallback } from 'react'
import { useTranslations } from 'next-intl'
import { useSearchStore } from '@/store/use-search-store'
import { getSearchQueryFromQueryStore } from '@/lib/search-utils'
import { useRouter } from '@/i18n/navigation'
import { useSearchParams } from 'next/navigation'
import { ChevronDown, ChevronRight, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'

export function CustomFacetOption({
  term,
  label,
  buckets,
}: {
  term: string
  label: string
  buckets: { key: string; doc_count: number }[]
}) {
  const t = useTranslations()
  const router = useRouter()
  const searchParams = useSearchParams()
  const advanced = useSearchStore((s) => s.advanced)
  const facetOptions = useSearchStore((s) => s.facetOptions)

  const getArray = useCallback(
    (type: '+' | '-'): string[] => {
      const fcLabel = 'fc-' + term
      if (!advanced.fc || !advanced.fc[fcLabel]) return []
      return advanced.fc[fcLabel][type] || []
    },
    [advanced.fc, term]
  )

  const initialOpen = !!(
    facetOptions[term]?.open ||
    getArray('-').length > 0 ||
    getArray('+').length > 0
  )
  const [open, setOpen] = useState(initialOpen)

  const checkedValues = useMemo(() => {
    const checked: Record<string, boolean> = {}
    const fcLabel = 'fc-' + term
    for (const bucket of buckets) {
      const obj = advanced.fc[fcLabel]
      checked[bucket.key] = !!(obj && obj['+'].includes(bucket.key))
    }
    return checked
  }, [buckets, advanced.fc, term])

  const notExcluded = getArray('-')

  const message = useMemo(() => {
    const size = buckets.length
    let prefix = ''
    if (size === 50) {
      prefix = t('top_prefix')
    }
    return prefix + size.toLocaleString() + t('items_count_suffix')
  }, [buckets.length, t])

  if (buckets.length === 0 && notExcluded.length === 0) return null

  const handleChange = (key: string) => {
    const fcLabel = 'fc-' + term
    const obj = advanced.fc[fcLabel]
    if (obj && obj['+'].includes(key)) {
      useSearchStore.getState().removeAdvanced({
        label: fcLabel,
        values: [key],
        type: 'fc',
      })
    } else {
      useSearchStore.getState().setAdvanced({
        label: fcLabel,
        values: [key],
        type: 'fc',
      })
    }
  }

  const handleExclude = (key: string) => {
    useSearchStore.getState().setAdvanced({
      label: 'fc-' + term,
      values: ['-' + key],
      type: 'fc',
    })
    updateQuery()
  }

  const handleRemoveExclude = (key: string) => {
    useSearchStore.getState().removeAdvanced({
      label: 'fc-' + term,
      values: ['-' + key],
      type: 'fc',
    })
    updateQuery()
  }

  const updateQuery = () => {
    const state = useSearchStore.getState()
    const query = getSearchQueryFromQueryStore(state, searchParams?.get('u') || undefined)
    query.from = '0'
    const params = new URLSearchParams()
    for (const [key, val] of Object.entries(query)) {
      if (Array.isArray(val)) val.forEach((v) => params.append(key, v))
      else params.append(key, val)
    }
    router.push(`/search?${params.toString()}`)
  }

  const displayLabel = label.startsWith('_') ? label.slice(1) : label

  return (
    <div className="mb-3 border rounded-lg overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between bg-muted px-3 py-2.5 text-left hover:bg-muted/80 transition-colors"
      >
        <span className="text-sm font-medium">
          {displayLabel} <span className="text-muted-foreground font-normal">({message})</span>
        </span>
        {open ? <ChevronDown className="w-4 h-4 text-muted-foreground" /> : <ChevronRight className="w-4 h-4 text-muted-foreground" />}
      </button>
      {open && (
        <div>
          <div className="max-h-96 overflow-y-auto">
            {buckets.map((bucket, i) => (
              <div key={i} className="flex items-center justify-between border-b border-border/50 px-3 py-1.5">
                <label className={`flex items-center gap-2 cursor-pointer text-sm flex-1 ${term.includes('Phone/Word') ? 'phone' : ''}`}>
                  <Checkbox
                    checked={!!checkedValues[bucket.key]}
                    onCheckedChange={() => handleChange(bucket.key)}
                  />
                  {['Item Type', 'Sub Type', 'Unit'].includes(term)
                    ? t(bucket.key)
                    : bucket.key}
                </label>
                <span className="text-xs text-muted-foreground mx-2">
                  {bucket.doc_count.toLocaleString()}
                </span>
                {!checkedValues[bucket.key] && (
                  <button
                    onClick={() => handleExclude(bucket.key)}
                    className="text-muted-foreground hover:text-destructive transition-colors"
                    aria-label={`${t('exclude')} ${bucket.key}`}
                  >
                    <X className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            ))}
          </div>

          {notExcluded.map((key, i) => (
            <div
              key={`not-${i}`}
              className="flex items-center px-3 py-1.5 border-t cursor-pointer hover:bg-accent"
              onClick={() => handleRemoveExclude(key)}
            >
              <span className="text-destructive mr-2 text-sm font-bold">-</span>
              <span className="text-sm">{key}</span>
            </div>
          ))}

          <div className="px-3 py-2 border-t">
            <Button onClick={updateQuery} size="sm">
              {t('update')}
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
